# Generated by Django 4.0.3 on 2022-03-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0036_auto_20190410_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='tel',
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('Not Known', 'Not Known')], default='male', max_length=100, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Dr', 'Dr'), ('Sir', 'Sir'), ('Madam', 'Madam')], default='Mr', max_length=80, null=True, verbose_name='Title'),
        ),
    ]
