# Generated by Django 3.2.6 on 2022-04-04 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_auto_20220404_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
    ]
