# Generated by Django 4.0.3 on 2022-03-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190410_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
